"""migration

Revision ID: 830f764b46a1
Revises: 
Create Date: 2019-08-05 08:11:40.068058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830f764b46a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.add_column('comments', sa.Column('comment', sa.String(), nullable=True))
    op.add_column('comments', sa.Column('title', sa.String(length=250), nullable=True))
    op.drop_column('comments', 'poted')
    op.drop_column('comments', 'posted')
    op.drop_column('comments', 'pitch_id')
    op.drop_column('comments', 'pitch_comment')
    op.drop_column('comments', 'user_id')
    op.drop_column('comments', 'full_time')
    op.drop_column('comments', 'pitch_title')
    op.drop_column('comments', 'name')
    op.add_column('pitches', sa.Column('description', sa.String(length=250), nullable=True))
    op.add_column('pitches', sa.Column('title', sa.String(length=250), nullable=True))
    op.create_foreign_key(None, 'pitches', 'users', ['user_id'], ['id'])
    op.drop_column('pitches', 'posted')
    op.drop_column('pitches', 'pitch_id')
    op.drop_column('pitches', 'pitch_comment')
    op.drop_column('pitches', 'full_time')
    op.drop_column('pitches', 'pitch_title')
    op.drop_column('pitches', 'name')
    op.add_column('users', sa.Column('code', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('pass_secure', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_column('users', 'comments_id')
    op.drop_column('users', 'role_id')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'full_time')
    op.drop_column('users', 'name')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('full_time', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('comments_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'username')
    op.drop_column('users', 'pass_secure')
    op.drop_column('users', 'id')
    op.drop_column('users', 'code')
    op.add_column('pitches', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('pitch_title', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('full_time', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('pitch_comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('posted', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'title')
    op.drop_column('pitches', 'description')
    op.add_column('comments', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('pitch_title', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('full_time', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('pitch_comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('posted', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('poted', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'title')
    op.drop_column('comments', 'comment')
    op.create_table('role',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('full_time', sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.create_table('profile_photos',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pic_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
