"""Initial Migration

Revision ID: 997e53907dbf
Revises: d76b48e20715
Create Date: 2019-08-06 16:11:36.911404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997e53907dbf'
down_revision = 'd76b48e20715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category', sa.String(), nullable=True))
    op.drop_column('pitches', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'category')
    # ### end Alembic commands ###
